### ISSUE TITLE
Erroneous Display on Ravenspeaker Thelnaas

### ISSUE THREAD

**Issue by wheatbread** [TekNoLogic/GnomishInboxShrinker#3]
Hello!  GnomishVendorShrinker causes this npc (http://www.wowhead.com/npc=96130/ravenspeaker-thelnaas) to bug out in his displayed goods.  The first item displays fine, then the rest is either covered by a gray screen, or will show the goods that were last seen on the previous merchant you talked to, and not the actual goods he has for sale. 

I really enjoy this addon, and thank you for sharing it!

**Comment by Talyrius** [comment]
This is the wrong repository and there is already an open issue for this. See TekNoLogic/GnomishVendorShrinker#35.

**Comment by wheatbread** [comment]
You're right
